server:
  port: 8901

spring:
  application:
    name: dubbo-comsumer

nacos:
  server-address: 192.168.131.129
  port: 8848

dubbo:
  registry:
    address: nacos://${nacos.server-address}:${nacos.port}