server:
  port: 8902

spring:
  application:
    name: dubbo-provider

nacos:
  server-address: 192.168.131.129
  port: 8848

dubbo:
  registry:
    address: nacos://${nacos.server-address}:${nacos.port}
  scan:
    base-packages: com.mm.api
  protocol:
    name: dubbo
    port: -1